Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -21,17 +21,6 @@ jobs:
       - name: Create container
         run: docker build -t jscott932/app-java-demo:latest .
 
-      - name: Endor Labs Container Scan
-        run: |
-          curl https://api.endorlabs.com/download/latest/endorctl_linux_amd64 -o endorctl
-          echo "$(curl -s https://api.endorlabs.com/sha/latest/endorctl_linux_amd64)  endorctl" | sha256sum -c;
-            if [ $? -ne 0 ]; then 
-            echo "Integrity check failed"; 
-            exit 1;
-          fi
-          chmod +x ./endorctl
-          ./endorctl scan --container=jscott932/app-java-demo:latest --dependencies --secrets --git-logs --tools --path=./ --enable-github-action-token=true -n demo -a https://api.staging.endorlabs.com
-          
       - name: Get Image Digest to Sign
         run: |
          IMAGE_SHA=$(docker inspect jscott932/app-java-demo:latest | jq -r '.[].Id')
@@ -42,24 +31,20 @@ jobs:
       - name: Container Sign
         uses: endorlabs/github-action/sign@main
         with:
-          namespace: "yolo"
+          api: https://api.staging.endorlabs.com
+          namespace: "demo"
           artifact_name: ${{ env.ARTIFACT }}
 
-      - name: Run Tests
-        run: |
-          mvn test
-          
       - name: Endor Labs Scan
-        uses: endorlabs/github-action@main
-        with:
-          namespace: "yolo"
-          scan_summary_output_type: "table"
-          pr: "false"
-          enable_github_action_token: "true"
-          scan_dependencies: "true"
-          scan_secrets: "true"
-          scan_git_logs: "true"
-          scan_tools: "true"
+        run: |
+          curl https://api.endorlabs.com/download/latest/endorctl_linux_amd64 -o endorctl
+          echo "$(curl -s https://api.endorlabs.com/sha/latest/endorctl_linux_amd64)  endorctl" | sha256sum -c;
+            if [ $? -ne 0 ]; then 
+            echo "Integrity check failed"; 
+            exit 1;
+          fi
+          chmod +x ./endorctl
+          ./endorctl scan --container=jscott932/app-java-demo:latest --dependencies --secrets --git-logs --tools --path=./ --enable-github-action-token=true -n demo -a https://api.staging.endorlabs.com
 
       - name: Get Image Digest to Verify
         run: |
@@ -71,9 +56,7 @@ jobs:
       - name: Container verify
         uses: endorlabs/github-action/verify@main
         with:
-          namespace: "yolo"
+          namespace: "demo"
+          api: https://api.staging.endorlabs.com
           artifact_name: ${{ env.VERIFY_ARTIFACT }}
           certificate_oidc_issuer: "https://token.actions.githubusercontent.com"
-          
-      - name: Push to Docker Hub
-        run: docker push jscott932/app-java-demo:latest
