Update release to try containers

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -12,7 +12,6 @@ jobs:
       id-token: write
       contents: read
     steps:
-    
       - name: Checkout code
         uses: actions/checkout@v3
         
@@ -21,6 +20,17 @@ jobs:
 
       - name: Create container
         run: docker build -t jscott932/app-java-demo:latest .
+
+      - name: Endor Labs Container Scan
+        run: |
+          curl https://api.endorlabs.com/download/latest/endorctl_linux_amd64 -o endorctl
+          echo "$(curl -s https://api.endorlabs.com/sha/latest/endorctl_linux_amd64)  endorctl" | sha256sum -c;
+            if [ $? -ne 0 ]; then 
+            echo "Integrity check failed"; 
+            exit 1;
+          fi
+          chmod +x ./endorctl
+          ./endorctl scan --container=jscott932/app-java-demo:latest --path=./
           
       - name: Get Image Digest to Sign
         run: |
@@ -51,15 +61,6 @@ jobs:
           scan_git_logs: "true"
           scan_tools: "true"
 
-      - name: Run SAST
-        run: python3 -m pip install semgrep && semgrep scan
-      
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
       - name: Get Image Digest to Verify
         run: |
          VERIFY_SHA=$(docker inspect jscott932/app-java-demo:latest | jq -r '.[].Id')
@@ -73,19 +74,6 @@ jobs:
           namespace: "yolo"
           artifact_name: ${{ env.VERIFY_ARTIFACT }}
           certificate_oidc_issuer: "https://token.actions.githubusercontent.com"
-
+          
       - name: Push to Docker Hub
         run: docker push jscott932/app-java-demo:latest
-
-      - name: Endor Labs Container Scan
-        uses: endorlabs/github-action@containers
-        with:
-          namespace: "yolo"
-          scan_summary_output_type: "table"
-          pr: "false"
-          enable_github_action_token: "true"
-          scan_container: true
-          scan_dependencies: false
-          image: jscott932/app-java-demo:latest
-          project_name: container-app-java-demo
-          
